### ISSUE TITLE
Integrate PitchRx 1.8.4.  Cannot access 2017 regular season data from MLBAM

### ISSUE THREAD

**Issue by jrbattles** [fire-ants/mlb-analytics-ant#12]

**Comment by jrbattles** [comment]
issue logged in base PitchRx package.  Carson Sievert (owner) has labeled it as a Help Wanted and has stated he is looking for a pull request from the community.

**Comment by jrbattles** [comment]
New version of PitchRx installed.  1.8.4 resolves the issue but only on Windows platform.  Unable to get it working on MacOS.   Not yet tested on native ubuntu inside container.

**Comment by dancohen21** [comment]
PitchRx is no longer a requirement of analytics ant
